<?php

namespace Database\Seeders;

use App\Models\Qualifiers\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["name" => "Afeganistão", "e_name" => "Afghanistan"],
            ["name" => "África do Sul", "e_name" => "South Africa"],
            ["name" => "Albânia", "e_name" => "Albania"],
            ["name" => "Alemanha", "e_name" => "Germany"],
            ["name" => "Angola", "e_name" => "Angola"],
            ["name" => "Arábia Saudita", "e_name" => "Saudi Arabia"],
            ["name" => "Argélia", "e_name" => "Algeria"],
            ["name" => "Argentina", "e_name" => "Argentina"],
            ["name" => "Armênia", "e_name" => "Armenia"],
            ["name" => "Austrália", "e_name" => "Australia"],
            ["name" => "Áustria", "e_name" => "Austria"],
            ["name" => "Azerbaijão", "e_name" => "Azerbaijan"],
            ["name" => "Bahamas", "e_name" => "Bahamas"],
            ["name" => "Bahrein", "e_name" => "Bahrain"],
            ["name" => "Bangladesh", "e_name" => "Bangladesh"],
            ["name" => "Barbados", "e_name" => "Barbados"],
            ["name" => "Belarus", "e_name" => "Belarus"],
            ["name" => "Bélgica", "e_name" => "Belgium"],
            ["name" => "Belize", "e_name" => "Belize"],
            ["name" => "Benin", "e_name" => "Benin"],
            ["name" => "Bermudas", "e_name" => "Bermuda"],
            ["name" => "Bolívia", "e_name" => "Bolivia"],
            ["name" => "Bósnia-Herzegóvina", "e_name" => "Bosnia & Herzegovina"],
            ["name" => "Botsuana", "e_name" => "Botswana"],
            ["name" => "Brasil", "e_name" => "Brazil"],
            ["name" => "Brunei", "e_name" => "Brunei"],
            ["name" => "Bulgária", "e_name" => "Bulgaria"],
            ["name" => "Burkina Fasso", "e_name" => "Burkina Faso"],
            ["name" => "Burundi", "e_name" => "Burundi"],
            ["name" => "Butão", "e_name" => "Bhutan"],
            ["name" => "Cabo Verde", "e_name" => "Cape Verde"],
            ["name" => "Camarões", "e_name" => "Cameroon"],
            ["name" => "Camboja", "e_name" => "Cambodia"],
            ["name" => "Canadá", "e_name" => "Canada"],
            ["name" => "Canárias", "e_name" => "Canary Islands"],
            ["name" => "Cazaquistão", "e_name" => "Kazakhstan"],
            ["name" => "Chade", "e_name" => "Chad"],
            ["name" => "Chile", "e_name" => "Chile"],
            ["name" => "China", "e_name" => "China"],
            ["name" => "Chipre", "e_name" => "Cyprus"],
            ["name" => "Cingapura", "e_name" => "Singapore"],
            ["name" => "Colômbia", "e_name" => "Colombia"],
            ["name" => "Comores", "e_name" => "Comoros"],
            ["name" => "Congo", "e_name" => "Congo (Republic)"],
            ["name" => "Coréia do Norte", "e_name" => "North Korea"],
            ["name" => "Coréia do Sul", "e_name" => "South Korea"],
            ["name" => "Costa do Marfim", "e_name" => "Côte d¿Ivoire"],
            ["name" => "Costa Rica", "e_name" => "Costa Rica"],
            ["name" => "Croácia", "e_name" => "Croatia"],
            ["name" => "Cuba", "e_name" => "Cuba"],
            ["name" => "Curaçao", "e_name" => "Curaçao"],
            ["name" => "Dinamarca", "e_name" => "Denmark"],
            ["name" => "Egito", "e_name" => "Egypt"],
            ["name" => "El Salvador", "e_name" => "El Salvador"],
            ["name" => "Emirados Árabes Unidos", "e_name" => "United Arab Emirates"],
            ["name" => "Equador", "e_name" => "Ecuador"],
            ["name" => "Eritréia", "e_name" => "Eritrea"],
            ["name" => "Escócia", "e_name" => "Scotland"],
            ["name" => "Eslováquia", "e_name" => "Slovakia"],
            ["name" => "Eslovênia", "e_name" => "Slovenia"],
            ["name" => "Espanha", "e_name" => "Spain"],
            ["name" => "Estados Unidos", "e_name" => "United States"],
            ["name" => "Estônia", "e_name" => "Estonia"],
            ["name" => "Etiópia", "e_name" => "Ethiopia"],
            ["name" => "Fiji", "e_name" => "Fiji"],
            ["name" => "Filipinas", "e_name" => "Philippines"],
            ["name" => "Finlândia", "e_name" => "Finland"],
            ["name" => "França", "e_name" => "France"],
            ["name" => "Gabão", "e_name" => "Gabon"],
            ["name" => "Gâmbia", "e_name" => "Gambia"],
            ["name" => "Gana", "e_name" => "Ghana"],
            ["name" => "Geórgia", "e_name" => "Georgia"],
            ["name" => "Gibraltar", "e_name" => "Gibraltar"],
            ["name" => "Granada", "e_name" => "Grenada"],
            ["name" => "Grécia", "e_name" => "Greece"],
            ["name" => "Groelândia", "e_name" => "Greenland"],
            ["name" => "Guadalupe", "e_name" => "Guadeloupe"],
            ["name" => "Guatemala", "e_name" => "Guatemala"],
            ["name" => "Guernsey", "e_name" => "Guernsey"],
            ["name" => "Guiana", "e_name" => "Guyana"],
            ["name" => "Guiana Francesa", "e_name" => "French Guiana"],
            ["name" => "Guiné", "e_name" => "Guinea"],
            ["name" => "Guiné Equatorial", "e_name" => "Equatorial Guinea"],
            ["name" => "Guiné-Bissau", "e_name" => "Guinea-Bissau"],
            ["name" => "Haiti", "e_name" => "Haiti"],
            ["name" => "Holanda", "e_name" => "Netherlands"],
            ["name" => "Honduras", "e_name" => "Honduras"],
            ["name" => "Hong Kong", "e_name" => "Hong Kong"],
            ["name" => "Hungria", "e_name" => "Hungary"],
            ["name" => "Iêmen", "e_name" => "Yemen"],
            ["name" => "Ilhas Cayman", "e_name" => "Cayman Islands"],
            ["name" => "Ilhas Salomão", "e_name" => "Solomon Islands"],
            ["name" => "Ilhas Seychelles", "e_name" => "Seychelles"],
            ["name" => "Índia", "e_name" => "India"],
            ["name" => "Indonésia", "e_name" => "Indonesia"],
            ["name" => "Inglaterra", "e_name" => "England"],
            ["name" => "Irã", "e_name" => "Iran"],
            ["name" => "Iraque", "e_name" => "Iraq"],
            ["name" => "Irlanda", "e_name" => "Ireland"],
            ["name" => "Irlanda do Norte", "e_name" => "Northern Ireland"],
            ["name" => "Islândia", "e_name" => "Iceland"],
            ["name" => "Israel", "e_name" => "Israel"],
            ["name" => "Itália", "e_name" => "Italy"],
            ["name" => "Jamaica", "e_name" => "Jamaica"],
            ["name" => "Japão", "e_name" => "Japan"],
            ["name" => "Jersey", "e_name" => "Jersey"],
            ["name" => "Jordânia", "e_name" => "Jordan"],
            ["name" => "Kiribati", "e_name" => "Kiribati"],
            ["name" => "Kosovo", "e_name" => "Kosovo"],
            ["name" => "Kuait", "e_name" => "Kuwait"],
            ["name" => "Laos", "e_name" => "Laos"],
            ["name" => "Lesoto", "e_name" => "Lesotho"],
            ["name" => "Letônia", "e_name" => "Latvia"],
            ["name" => "Líbano", "e_name" => "Lebanon"],
            ["name" => "Libéria", "e_name" => "Liberia"],
            ["name" => "Líbia", "e_name" => "Libya"],
            ["name" => "Liechtenstein", "e_name" => "Liechtenstein"],
            ["name" => "Lituânia", "e_name" => "Lithuania"],
            ["name" => "Luxemburgo", "e_name" => "Luxembourg"],
            ["name" => "Macau", "e_name" => "Macau"],
            ["name" => "Macedônia (República Yugoslava)", "e_name" => "Macedonia (FYROM)"],
            ["name" => "Madagascar", "e_name" => "Madagascar"],
            ["name" => "Malásia", "e_name" => "Malaysia"],
            ["name" => "Malaui", "e_name" => "Malawi"],
            ["name" => "Mali", "e_name" => "Mali"],
            ["name" => "Malta", "e_name" => "Malta"],
            ["name" => "Marrocos", "e_name" => "Morocco"],
            ["name" => "Martinica", "e_name" => "Martinique"],
            ["name" => "Maurício", "e_name" => "Mauritius"],
            ["name" => "Mauritânia", "e_name" => "Mauritania"],
            ["name" => "México", "e_name" => "Mexico"],
            ["name" => "Moçambique", "e_name" => "Mozambique"],
            ["name" => "Moldova", "e_name" => "Moldova"],
            ["name" => "Mônaco", "e_name" => "Monaco"],
            ["name" => "Mongólia", "e_name" => "Mongolia"],
            ["name" => "Montenegro", "e_name" => "Montenegro"],
            ["name" => "Montserrat", "e_name" => "Montserrat"],
            ["name" => "Myanma", "e_name" => "Myanmar (Burma)"],
            ["name" => "Namíbia", "e_name" => "Namibia"],
            ["name" => "Nepal", "e_name" => "Nepal"],
            ["name" => "Nicarágua", "e_name" => "Nicaragua"],
            ["name" => "Níger", "e_name" => "Niger"],
            ["name" => "Nigéria", "e_name" => "Nigeria"],
            ["name" => "Noruega", "e_name" => "Norway"],
            ["name" => "Nova Caledônia", "e_name" => "New Caledonia"],
            ["name" => "Nova Zelândia", "e_name" => "New Zealand"],
            ["name" => "Omã", "e_name" => "Oman"],
            ["name" => "País de Gales", "e_name" => "Wales"],
            ["name" => "Palestina", "e_name" => "Palestine"],
            ["name" => "Panamá", "e_name" => "Panama"],
            ["name" => "Papua-Nova Guiné", "e_name" => "Papua New Guinea"],
            ["name" => "Paquistão", "e_name" => "Pakistan"],
            ["name" => "Paraguai", "e_name" => "Paraguay"],
            ["name" => "Peru", "e_name" => "Peru"],
            ["name" => "Polinésia Francesa", "e_name" => "French Polynesia"],
            ["name" => "Polônia", "e_name" => "Poland"],
            ["name" => "Porto Rico", "e_name" => "Puerto Rico"],
            ["name" => "Portugal", "e_name" => "Portugal"],
            ["name" => "Qatar", "e_name" => "Qatar"],
            ["name" => "Quênia", "e_name" => "Kenya"],
            ["name" => "Quirguistão", "e_name" => "Kyrgyzstan"],
            ["name" => "República Centro-Africana", "e_name" => "Central African Republic"],
            ["name" => "República Democrática do Congo", "e_name" => "Congo (DRC)"],
            ["name" => "República Dominicana", "e_name" => "Dominican Republic"],
            ["name" => "República Tcheca", "e_name" => "Czech Republic"],
            ["name" => "Romênia", "e_name" => "Romania"],
            ["name" => "Ruanda", "e_name" => "Rwanda"],
            ["name" => "Rússia", "e_name" => "Russia"],
            ["name" => "Senegal", "e_name" => "Senegal"],
            ["name" => "Serra Leoa", "e_name" => "Sierra Leone"],
            ["name" => "Sérvia", "e_name" => "Serbia"],
            ["name" => "Síria", "e_name" => "Syria"],
            ["name" => "Somália", "e_name" => "Somalia"],
            ["name" => "Sri Lanka", "e_name" => "Sri Lanka"],
            ["name" => "Sudão", "e_name" => "Sudan"],
            ["name" => "Sudão do Sul", "e_name" => "South Sudan"],
            ["name" => "Suécia", "e_name" => "Sweden"],
            ["name" => "Suíça", "e_name" => "Switzerland"],
            ["name" => "Suriname", "e_name" => "Suriname"],
            ["name" => "Svalbard", "e_name" => "Svalbard & Jan Mayen"],
            ["name" => "Tadjiquistão", "e_name" => "Tajikistan"],
            ["name" => "Tailândia", "e_name" => "Thailand"],
            ["name" => "Taiwan", "e_name" => "Taiwan"],
            ["name" => "Tanzânia", "e_name" => "Tanzania"],
            ["name" => "Timor-Leste", "e_name" => "Timor-Leste"],
            ["name" => "Togo", "e_name" => "Togo"],
            ["name" => "Tonga", "e_name" => "Tonga"],
            ["name" => "Trinidad e Tobago", "e_name" => "Trinidad & Tobago"],
            ["name" => "Tunísia", "e_name" => "Tunisia"],
            ["name" => "Turcomenistão", "e_name" => "Turkmenistan"],
            ["name" => "Turquia", "e_name" => "Turkey"],
            ["name" => "Tuvalu", "e_name" => "Tuvalu"],
            ["name" => "Ucrânia", "e_name" => "Ukraine"],
            ["name" => "Uganda", "e_name" => "Uganda"],
            ["name" => "Uruguai", "e_name" => "Uruguay"],
            ["name" => "Uzbequistão", "e_name" => "Uzbekistan"],
            ["name" => "Vanuatu", "e_name" => "Vanuatu"],
            ["name" => "Vaticano", "e_name" => "Vatican City"],
            ["name" => "Venezuela", "e_name" => "Venezuela"],
            ["name" => "Vietnã", "e_name" => "Vietnam"],
            ["name" => "Zâmbia", "e_name" => "Zambia"],
            ["name" => "Zimbábue", "e_name" => "Zimbabwe"],
        ];

        foreach ($countries as $arr) {
            Country::create($arr);
        }
    }
}
